# Generated by Django 5.2.4 on 2025-07-06 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Book", "0002_book_price"),
    ]

    operations = [
        migrations.CreateModel(
            name="Course",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="Student",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("marks", models.IntegerField()),
                ("courses", models.ManyToManyField(to="Book.course")),
            ],
        ),
    ]
