# Generated by Django 5.2.4 on 2025-07-13 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("CityChoice", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Employee",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("salary", models.DecimalField(decimal_places=2, max_digits=10)),
                ("address", models.TextField()),
            ],
        ),
    ]
