# Generated by Django 5.2.4 on 2025-07-14 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("CityChoice", "0002_employee"),
    ]

    operations = [
        migrations.CreateModel(
            name="Department",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("department_name", models.CharField(max_length=50)),
            ],
        ),
    ]
